alg = input('Digite algo: ')
print('O valor primitivo é: ', type(alg))
print('Só tem valores numéricos?', alg.isnumeric())
print('Tem valores alfanuméricos?', alg.isalnum())
print('Só tem espaços?', alg.isspace())
print('Só temos letras?', alg.isalpha())
print('Está em maiúsculo?', alg.isupper())
print("Está em minúsculo?", alg.islower())
print('Está capitalizada?', alg.istitle())
#Módulo1